### ISSUE TITLE
Customize stories feature

### ISSUE THREAD

**Issue by MichaelMaltsev** [redmadrobot-tomsk/android-stories#4]
## В данном issue будут описаны предложения/исследования фичи кастомизации сторисов.

Сначала нужно определиться с необходимыми вьюхами у сториса. 
Для этого, ниже приведены иерархия вьюх в уже готовых лэйаутах.

- Сторис StoryFragment:
- Прогресс бар сториса (StoriesProgressView)
- Кнопка закрытия (ImageView/Button)
- Фрейм истории (StoryFrameView)

Фрейм сториса StoryFrameView:
- Картинку фрейма (ImageView)
- Контент фрейма (StoryFrameContentView)
- Прогресс бар загрузки фрейма (ProgressBar)
- Лэйаут ошибки (View) - кнопка перезагрузки, обязателен коллбек onRefresh

Контент фрейма StoryFrameContentView:
- Заголовок (TextView)
- Подзаголовок (TextView)
- Подробное описание (TextView)
- Кнопка действия (Button) - должен быть onClick

Следовательно, у сториса следующие основные элементы:
- Прогресс бар
- Картинка фрейма
- Текст фрейма (заголовок, подзаголовок, подробнее)
- Кнопка фрейма (обработка юрла по клику)
- Вью ошибки

Нужно добавить возможность замены имеющихся лэйаутов сторисов/фреймов/контента на свой собственный.
Другой вопрос - как вставить собственные лэйауты в StoryFragment. 
Как вариант, можно передавать в конструктор StoryFragment указанные выше вьюхи. К примеру:

```
class StoryFragment : Fragment(), StoryListener {
    companion object {
        fun newInstance(story: Story, views: StoryViews): Fragment {
            ...
            return StoryFragment()
        }
    }
}

// Все основные элементы сториса
data class StoryViews(
    val progressBar: StoriesProgressView,
    val image: ImageView,
    val title: TextView,
    val subTitle: TextView,
    val description: TextView,
    val button: Button?,
    val errorView: View
)
```

Довольно простой способ, но тогда не получится управлять расположением элементов. 
По-хорошему, надо передавать именно R.layout.my_layout, но тогда, скорее всего, придется проверять наличие всех элементов  в рантайме и выкидывать эксепшн при отсутствии.

Если ничего не пропускаю, реализация коллбэков типа нажатия кнопки сторисов уже реализована (добавлять кастомизацию и для этого было бы еще труднее), поэтому надо сначала решить с вьюхами.

Следующий вопрос - _когда_ добавлять кастомные вьюхи. 
StoryFragment создается в FragmentAdapter-е, так что, скорее всего, вьюхи/лэйаут надо передать именно в него.

В итоге, нужно подумать о следующих моментах:
1. Как добавлять кастомные вьюхи - передавать инстансы в конструктор или передавать лэйаут? Во втором случае, как создать контракт о необходимых вью?
2. Когда совершить замену вьюх на кастомные? Скорее всего, передачу можно делать при инициализации либы, а эти вьюхи/лэйаут будут передаваться при создании фрагмента (в fragment adapter).
3. Надо определиться с максимальным минимумом необходимых вьюх. Потенциально, могут не понадобиться заголовки сторисов, соответственно, и в лэйауте вьюхи с текстом требовать не надо.

**Comment by MichaelMaltsev** [comment]
Отдельно сделал кривенький скелет сториса с главными элементами (кнопки нет, она опциональна)

![image](https://user-images.githubusercontent.com/89060414/163773712-dbb94aaa-efea-461d-95db-93041d4831c0.png)

**Comment by MichaelMaltsev** [comment]
Есть еще одна идея реализации кастомизации - имплементировать паттерн "адаптер", аналогично адаптеру у ресайклера. Можно сделать базовый адаптер, в который перенести реализацию базовых вещей, а остальное будет в руках программиста.
Единственный минус - пока трудно представляется реализация способа. Возможно, это будет слишком сложно.

**Comment by AlexeiYakimov** [comment]
`fun newInstance(story: Story, views: StoryViews): Fragment {
            ...
            return StoryFragment()
        }`
нам сразу же не подходит: вью должны создаваться в контексте фрагмента и на ЖЦ фрагмента. Плюс мы совершенно никак не сможем передать объекты вью через аргументы, поэтому на самом деле вариантов немного: мы ОБЯЗАНЫ надувать/создавать StoryFrameView после создания вью фрагмента.

**Comment by MichaelMaltsev** [comment]
Тогда можно сделать вот так: вынести всю логику в абстрактный класс BaseStoryFragment, где оставить основные вьюхи абстрактными, а в реализации оверрайднуть эти вьюхи.
```
abstract class BaseStoryFragment : Fragment(), StoryListener {

    protected abstract val storyFrameView: StoryFrameView
    protected abstract val progressView: StoriesProgressView
    protected abstract val imgClose: ImageView

    // Остальной код...
}

class StoryFragmentImpl : BaseStoryFragment() {

    private var _binding: FragmentStoryBinding? = null
    private val binding get() = _binding!!

    override val storyFrameView: StoryFrameView
        get() = binding.storyFrameView
    override val progressView: StoriesProgressView
        get() = binding.progressView
    override val imgClose: ImageView
        get() = binding.imgClose
}
```
Боялся лишь за то, что в процессе ЖЦ может выпасть NPE, когда будут запрашиваться оверрайднутые вьюхи, но геттеры, скорее всего, проблему решат)
Если норм, с остальными вьюхами нужно будет сделать так же, то есть, будет BaseStoryFrameView, BaseStoryContentView, BaseStoriesProgressView.

**Comment by AlexeiYakimov** [comment]
В принципе, все, что нам надо - это кастомизация собственно `StoryFrameView`, чтобы иметь возможность изменять вид фрейма. Прогресс и кнопка закрытия - стандартные компоненты. Максимум, что мы дадим с ними сделать - например, скрыть/показать.

Если мы хотим использовать отличную от стандартной вьюшку фрейма, нам надо:
1.  описать при помощи интерфейса все то, что должна уметь и содержать эта вьюшка.2. 

Можем ли мы описать при помощи интерфейса все то, что должна уметь и содержать эта вьюшка?

**Comment by AlexeiYakimov** [comment]
В принципе, все, что нам надо - это кастомизация собственно `StoryFrameView`, чтобы иметь возможность изменять вид фрейма. Прогресс и кнопка закрытия - стандартные компоненты. Максимум, что мы дадим с ними сделать - например, скрыть/показать.

Если мы хотим использовать отличную от стандартной вьюшку фрейма, нам надо просто заменить вьюшку стандартного фрейма на нашу кастомную, для этого:

- создаем абстрактный класс `BaseStoryFrameView` - он будет держателем логики с тачем, лиснером и сторифреймом.
- создаем реализацию `BaseStoryFrameView` - собственно то, что есть сейчас, будет использоваться по дефолту.
- в `BaseStoryFragment` добавляем метод создания фрейма, который в базовой реализации просто будет возвращать null
- все наследники `BaseStoryFragment`, если они хотят переопределить вьюшку, будут из метода возвращать свою реализацию BaseStoryFrameView - и в базовом классе мы будем ею подменять текущую заинфлейченную вьюшку.

Возможно, что-то упустил.

**Comment by MichaelMaltsev** [comment]
В ПР-е #5 реализовал примерно по комментарию Леши.
